#!/bin/bash

NAME="jellyfin"
DIRECTORY="PROJECT_DIRECTORY_HERE"
FILE="PROJECT_DIRECTORY_HERE/docker-compose.yml"

if ! [[ $EUID -ne 0 ]]; then
	echo "This script should not be run with root/sudo privileges."
	exit 1
fi

CUR_USER=$(whoami)

START=1
if [ $# -ge 2 ]; then
	echo "Usage: $NAME <up|stop>"
	exit 1
fi
if [ $# -eq 0 ]; then
	START=1
elif [ "$1" == "stop" ]; then
    START=0
elif [ "$1" == "up" ]; then
    START=1
else
   	echo "Usage: $NAME <up|stop>"
	exit 1
fi

if (( START )); then
    docker compose --file $FILE up -d --build
else
    docker compose --file $FILE stop
fi
