#!/bin/bash

#
# To remove sudo requirement, add this to /etc/udev/rules.d/backlight.rules
#
# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chgrp wheel /sys/class/backlight/intel_backlight/brightness"
# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chmod g+w /sys/class/backlight/intel_backlight/brightness"

old=`cat /sys/class/backlight/intel_backlight/brightness`
max=`cat /sys/class/backlight/intel_backlight/max_brightness`

change=$((max/20))

if [[ "$2" == "p" ]]; then
	change=$((max/100))
else
	if [[ "$1" == "down" ]] && [ "$old" -lt "$((change*2+1))" ]; then
		change=$((max/100))
	elif [[ "$1" == "up" ]] && [ "$old" -lt "$((change*2))" ]; then
		change=$((max/100))
	fi
	if [[ "$2" == "pp" ]]; then
		change=$((max/500))
	else
		if [[ "$1" == "down" ]] && [ "$old" -lt "$((change*2+1))" ]; then
			change=$((max/1000))
		elif [[ "$1" == "up" ]] && [ "$old" -lt "$((change*2))" ]; then
			change=$((max/1000))
		fi
	fi
fi

new=$old

if [[ "$1" == "down" ]]; then
	num=$((old))
	num=$((num-=change))
	if [ "$num" -lt "0" ]; then
		new=0
	else
		new=$num
	fi
fi	

if [[ "$1" == "up" ]]; then
	num=$((old))
	num=$((num+=change))
	if [ "$num" -gt "$max" ]; then
		new=$max
	else
		new=$num
	fi
fi	

echo $new | tee /sys/class/backlight/intel_backlight/brightness
