#!/bin/bash

compose_images=$(docker images --filter "label=com.docker.compose.project")
compose_images=$(echo "$compose_images" | awk 'NR>1 {system("echo " $1)}')

all_images=$(docker images)

for image in $compose_images; do
    all_images=$(echo "$all_images" | grep -v "$image")
done

all_images=$(echo "$all_images" | grep -v "<none>" | grep -v "REPOSITORY")

all_images=$(echo "$all_images" | tr -s ' ' | cut -d" " -f1,2 --output-delimiter=":")

for image in $all_images; do
    echo "Pulling $image"
    docker pull $image
done


# pull_images=$(echo "$all_images" | grep "latest")
# 
# pull_images=$(printf "REPOSITORY                    TAG                           IMAGE ID       CREATED        SIZE\n$pull_images")
# 
# echo "$pull_images" | awk 'NR>1 {system("docker pull " $1)}'

yes | docker system prune
