#!/usr/bin/env python3

import sqlite3
import os
import csv
import sys
import validators
from urllib.parse import urlparse

domains = []

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

def find_cookies_file():
    res = "cookies.sqlite"

    if not os.path.exists(res):
        eprint(res, "does not exist")
        sys.exit(1)

    return res

def extract_domains():
    if len(sys.argv) > 1:
        for url in sys.argv[1:]:
            if validators.domain(url):
                domains.append(url)
                continue
            parsed_url = urlparse(url)
            domain = parsed_url.netloc
            if domain and validators.domain(domain):
                domains.append(domain)
    else:
        eprint("Please provide one or more URLs as command-line arguments.")
        sys.exit(1)

def export_cookies_to_txt(sqlite_file, txt_file):
    """Exports cookies from SQLite to CSV format."""
    conn = sqlite3.connect(sqlite_file)
    cursor = conn.cursor()

    query = """
    SELECT host, path, isSecure, expiry, name, value 
    FROM moz_cookies
    WHERE 
    """
    for domain in domains:
        query += f"host='{domain}' OR "
    query += "host='poopoo';"

    cursor.execute(query)
    cookies = cursor.fetchall()

    with open(txt_file, 'w') as txtfile:
        for cookie in cookies:
            domain = cookie[0]
            path = cookie[1]
            secure = 'TRUE' if cookie[2] == '1' else 'FALSE'
            expiry = cookie[3]
            name = cookie[4]
            value = cookie[5]
            txtfile.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

    conn.close()

    res = ""
    with open(txt_file, 'r') as txtfile:
        res = txtfile.readlines() 
    res = "".join(res)
        
    return res


def main():
    sqlite_file = find_cookies_file()
    extract_domains()
    
    txt_file = 'cookies.txt'

    res = export_cookies_to_txt(sqlite_file, txt_file)
    print(res)

if __name__ == "__main__":
    main()

