#!/usr/bin/env python3

import sqlite3
import os
import csv
import sys
import validators
from urllib.parse import urlparse

domains = []

def find_cookies_file():
    res = "cookies.sqlite"

    if not os.path.exists(res):
        print(res, "does not exist")
        sys.exit(1)

    return res

def extract_domains():
    if len(sys.argv) > 1:
        for url in sys.argv[1:]:
            if validators.domain(url):
                domains.append(url)
                continue
            parsed_url = urlparse(url)
            domain = parsed_url.netloc
            if domain and validators.domain(domain):
                domains.append(domain)
    else:
        print("Please provide one or more URLs as command-line arguments.")
        sys.exit(1)

def export_cookies_to_txt(sqlite_file, txt_file):
    """Exports cookies from SQLite to CSV format."""
    conn = sqlite3.connect(sqlite_file)
    cursor = conn.cursor()

    query = """
    SELECT host, path, isSecure, expiry, name, value 
    FROM moz_cookies
    WHERE 
    """
    for domain in domains:
        query += f"host='{domain}' OR "
    query += "host='poopoo';"

    cursor.execute(query)
    cookies = cursor.fetchall()

    # Write the results to a CSV file
    #with open(csv_file, 'w', newline='') as file:
    #    writer = csv.writer(file)
    #    writer.writerow(['domain', 'path', 'secure', 'expiry', 'name', 'value'])
    #    for cookie in cookies:
    #        writer.writerow(cookie)
    with open(txt_file, 'w') as txtfile:
        for cookie in cookies:
            domain = cookie[0]
            path = cookie[1]
            secure = 'TRUE' if cookie[2] == '1' else 'FALSE'
            expiry = cookie[3]
            name = cookie[4]
            value = cookie[5]
            txtfile.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

    conn.close()

#def convert_csv_to_txt(csv_file, txt_file):
#    """Converts CSV format to the cookies.txt format."""
#    with open(csv_file, 'r') as csvfile, open(txt_file, 'w') as txtfile:
#        reader = csv.DictReader(csvfile)
#        for row in reader:
#            domain = row['domain']
#            path = row['path']
#            secure = 'TRUE' if row['secure'] == '1' else 'FALSE'
#            expiry = row['expiry']
#            name = row['name']
#            value = row['value']
#            txtfile.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

def main():
    sqlite_file = find_cookies_file()
    extract_domains()
    
    txt_file = 'cookies.txt'

    export_cookies_to_txt(sqlite_file, txt_file)

    print("Conversion completed. Check cookies.txt file.")

if __name__ == "__main__":
    main()

