#!/usr/bin/env python3

import sys
import requests
import subprocess

USE_COOKIES = True
COOKIES_LOCATION = "/tmp/kick-cookies.txt"


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def get_cookies():
    cmd_args = ["get-cookies", "kick.com"]

    cookies = subprocess.check_output(cmd_args).decode()

    with open(COOKIES_LOCATION, 'w') as f:
        f.write(cookies)


def download_clips(streamer):
    response = requests.get(f"https://kick.com/api/v2/channels/{streamer}/clips?cursor=0&sort=view&time=all")

    data = response.json()

    print(data)


def main():
    if len(sys.argv) != 2:
        eprint("Usage: kick-clips-dl <streamer>")
        sys.exit(1)

    streamer = sys.argv[1]

    if USE_COOKIES:
        get_cookies()
    
    # download_clips(streamer)
    

if __name__ == "__main__":
    main()