#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <directory>"
    exit 1
fi

# Check if the provided argument is a directory
if [ ! -d "$1" ]; then
    echo "Error: $1 is not a directory"
    exit 1
fi

# Loop through each PDF file
for file in "$1"/*.pdf; do
    filename=$(basename -- "$file" .pdf)
    dir=$(dirname "$file")

    # # Remove any tags on PDF
    # echo "Removing tags on \"$dir/$filename.pdf\""
    # pdftk "$dir/$filename.pdf" output "$dir/output_no_tags.pdf" uncompress
    # sed -i '/^\/StructTreeRoot/d' "$dir/output_no_tags.pdf"
    # pdftk "$dir/output_no_tags.pdf" output "$dir/$filename.pdf" compress
    # rm "$dir/output_no_tags.pdf"

    # OCR the PDF
    echo "ocrmypdf --skip-text \"$dir/$filename.pdf\" \"$dir/OCR_$filename.pdf\""
    ocrmypdf --skip-text "$dir/$filename.pdf" "$dir/OCR_$filename.pdf"
done
