#!/bin/bash

# Loop through each PDF file
for file in *.pdf; do
    # Extract the file name without extension
    filename=$(basename -- "$file" .pdf)
    # Convert PDF to PNG
    # convert "$filename.pdf" -density 600 "$filename.png"
    pdftoppm -png -r 150 "$filename.pdf" "$filename"
done
