#!/usr/bin/env bash

DUMMY_USER="del_prot"

if ! [[ $EUID -ne 0 ]]; then
	echo "This script must NOT be run with root/sudo privileges."
	exit 1
fi
CUR_USER=$(whoami)

if [ $# -ne 1 ]; then
    echo "Usage: $0 <directory_path>"
    exit 1
fi

dir_path="$1"

if [ ! -d "$dir_path" ]; then
    echo "Error: '$dir_path' is not a directory."
    exit 1
fi

# Add user if it doesn't exist
id -u $DUMMY_USER &>/dev/null || sudo useradd $DUMMY_USER

sudo chown $DUMMY_USER:$CUR_USER "$dir_path"
sudo chmod 1775 "$dir_path"

for file in "$dir_path"/*; do
    if [ -f "$file" ]; then
        echo "Protecting $(basename "$file")"
        sudo chown "$DUMMY_USER" "$file"
        sudo chmod 664 "$file"
    fi
done