#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run with root/sudo privileges."
	exit 1
fi

netlist=$(virsh net-list --inactive --name)

for network in $netlist; do
    virsh net-start $network
done
