#!/usr/bin/env bash
# wrappedhl
# Launch Hyprland with a simple wrapper

cd ~

# Variables
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24

export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

# Execute Hyprland
if [ -f /usr/bin/start-hyprland ]; then
   exec /usr/bin/start-hyprland >/dev/null 2>&1
else
   echo "No hyprland executable found"
   exit 1
fi
