#!/bin/bash

while ! pgrep -x "weston" > /dev/null; do
    sleep 1
done

while [ "$WAYLAND_DISPLAY" == "" ]; do
    sleep 1
done

# /usr/bin/waydroid session start

until /usr/bin/waydroid session start; do
    echo "Command exited with a non-zero exit code. Retrying..."
    sleep 1
done