services:
  mount-checker:
    build: mount-checker
    container_name: nextcloud-checker
    volumes:
      - /media:/media:ro
    healthcheck:
      test: ["CMD-SHELL", "[ -d /media/veracrypt1 ]"]
      interval: 1s
      timeout: 1s
      start_period: 0s
      retries: 2147483647
    stop_grace_period: 1s
    restart: unless-stopped

  mount-runner:
    build: mount-runner
    container_name: nextcloud-runner
    depends_on:
      mount-checker:
        condition: service_healthy
    volumes:
      - /media/veracrypt1:/media/veracrypt1:ro
    stop_grace_period: 1s
    restart: on-failure
  
  db:
    image: postgres:alpine
    container_name: nextcloud-db
    depends_on:
      mount-checker:
        condition: service_healthy
    volumes:
      - ./db:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    depends_on:
      mount-checker:
        condition: service_healthy
    restart: on-failure

  imaginary:
    image: h2non/imaginary:latest
    container_name: nextcloud-imaginary
    depends_on:
      mount-checker:
        condition: service_healthy
    command: -p 9000 -enable-url-source
    restart: on-failure

  app:
    build: .
    container_name: nextcloud-app
    depends_on:
      mount-checker:
        condition: service_healthy
    links:
      - db
      - redis
      - imaginary
    volumes:
      - ./nextcloud:/var/www/html:z
      - /media/veracrypt1:/opt/mount
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_INIT_HTACCESS=true
      - NEXTCLOUD_TRUSTED_DOMAINS="localhost nextcloud.local web 10.152.153.14"
      - PHP_MEMORY_LIMIT=12G
      - PHP_UPLOAD_LIMIT=16G
      - APACHE_BODY_LIMIT=0
    restart: on-failure
  
  web:
    build: ./web
    container_name: nextcloud-web
    depends_on:
      mount-checker:
        condition: service_healthy
    links:
      - app
    ports:
      - 8080:80
    volumes:
      - ./nextcloud:/var/www/html:z,ro
    # networks:
    #   - proxy-tier
    #   - default
    restart: on-failure

  proxy:
    build: ./proxy
    container_name: nextcloud-proxy
    depends_on:
      mount-checker:
        condition: service_healthy
    ports:
      - 80:80
      - 443:443
    links:
      - web
    volumes:
      - ./nextcloud:/var/www/html:z,ro
      - ./nextcloud.local.crt:/etc/ssl/certs/cert.crt:ro
      - ./nextcloud.local.key:/etc/ssl/private/cert.key:ro
    # networks:
    #   - proxy-tier
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
  
  cron:
    image: nextcloud:fpm
    container_name: nextcloud-cron
    depends_on:
      mount-checker:
        condition: service_healthy
    links:
      - db
      - redis
    volumes:
      - ./nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    stop_grace_period: 3s
    restart: on-failure

