version: "3"
services:
  tts:
    build:
      context: .
    ports:
      - "5002:5002"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
