FROM ghcr.io/coqui-ai/tts

#ENTRYPOINT "/usr/bin/python3 TTS/server/server.py --list_models"
#ENTRYPOINT "ls /bin"

#ENTRYPOINT ["/bin/sh"]
#CMD ["ls", "/bin"]
ENTRYPOINT ["/bin/bash"]
CMD ["-c", "ls /bin"]