version: "3"
services:
  gluetun-mullvad:
    container_name: gluetun-mullvad
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_PROTOCOL=tcp
      - OPENVPN_USER=<MULLVAD_USER_ID>
      - SERVER_CITIES=amsterdam
      - VPN_ENDPOINT_PORT=443
      - HTTPPROXY=on
      - SHADOWSOCKS=on
    ports:
      - 8880:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 1080:1080/tcp # Socks5
      - 1080:1080/udp # Socks5

  gluetun-socks5:
    image: serjs/go-socks5-proxy
    container_name: gluetun-socks5
    depends_on:
      - gluetun-mullvad
    network_mode: "service:gluetun-mullvad"
    restart: unless-stopped