services:
  gluetun-home:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=<MULLVAD_USER_ID>
      - VPN_ENDPOINT_PORT=443
      - HTTPPROXY=on
      - SHADOWSOCKS=on
    ports:
      - 8880:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    restart: unless-stopped
