version: "3"
services:
  fah0:
    image: foldingathome/fah-gpu:latest
    container_name: fah0
    group_add:
      - "RENDER_ID_HERE" # Change this to match your "render" host group id and remove this comment
      - "VIDEO_ID_HERE" # Change this to match your "video" host group id and remove this comment
    user: USER_ID_HERE:GROUP_ID_HERE
    volumes:
      - ./fah:/fah
    ports:
      - 7396:7396
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
