#!/bin/bash

if ! [[ $EUID -ne 0 ]]; then
        echo "This script should not be run with root/sudo privileges."
        exit 1
fi

last_part=$(($1 + 20))
ip="10.153.153.$last_part"

device=$(adb devices -l | grep $ip)

NO_IP=0
if [ "$device" == "" ]; then
    NO_IP=1
fi

transport_id=$(echo "$device" | awk -F 'transport_id:' '{print $2}' | awk '{print $1}')

SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

CUR_USER=$(whoami)

FOLDERS=$(ls -1 $SCRIPT_DIR/installer/apps | fzf -m --prompt="Select apks to install")

for folder in $FOLDERS; do
    directory="$SCRIPT_DIR/installer/apps/$folder"
    files=$(ls -1 $directory | grep ".apk")
    for file in $files; do
        apk_path=$directory/$file
        echo "Installing $file"
	if (( NO_IP )); then
            adb install $apk_path
	else
            adb -t $transport_id install $apk_path
	fi
    done
done