#!/bin/bash

if ! [[ $EUID -ne 0 ]]; then
	echo "This script must NOT be run with root/sudo privileges."
	exit 1
fi

# Initialize variables to store total size, photo count, and video count
total_size=0
photo_count=0
video_count=0

# Determine the directory to analyze
if [ $# -eq 0 ]; then
    # If no arguments are provided, use the current directory
    target_dir="."
elif [ $# -eq 1 ]; then
    # If one argument is provided, use it as the target directory
    target_dir="$1"
else
    # If more than one argument is provided, show usage message and exit
    echo "Usage: $0 [directory]"
    exit 1
fi

# Check if the specified directory exists
if [ ! -d "$target_dir" ]; then
    echo "Directory '$target_dir' not found."
    exit 1
fi

# Loop through each entry in the target directory
for entry in "$target_dir"/*/; do
    # Remove the trailing slash from the directory name
    dir=${entry%/}

    # Calculate the size of the directory
    size=$(du -sh "$dir" | cut -f1)
    unit=$(echo "$size" | grep -oE "[a-zA-Z]+")
    float=$(echo "$size" | sed "s/$unit//g")
    formatted_size=$(printf "%0.4g %s" $float "$unit")

    # Count the number of photos and videos in the directory
    photos=$(find "$dir" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | wc -l)
    videos=$(find "$dir" -maxdepth 1 -type f \( -iname "*.mp4" -o -iname "*.mov" -o -iname "*.avi" -o -iname "*.webm" \) | wc -l)

    dir_basename=$(basename "$dir")

    # Print the directory name, size, photo count, and video count
    echo "$dir_basename [${formatted_size}] [$photos photos, $videos videos]"

    # Update the total size, photo count, and video count
    total_size=$((total_size + $(du -s "$dir" | cut -f1)))
    photo_count=$((photo_count + photos))
    video_count=$((video_count + videos))
done

# Print the total size, photo count, and video count for the target directory
#echo "Total Size: $total_size, Total Photos: $photo_count, Total Videos: $video_count"
