#!/bin/bash

usage() {
    echo "Usage: $0 <input_file> <input_srt>"
    exit 1
}

if [ "$EUID" -eq 0 ]; then
    echo "Please do not run this script as root."
    exit 1
fi

if [ "$#" -ne 2 ]; then
    usage
fi

input_file="$1"
input_srt="$2"
if [ ! -f "$input_file" ]; then
    echo "File '$input_file' not found!"
    exit 1
fi
if [ ! -f "$input_srt" ]; then
    echo "File '$input_srt' not found!"
    exit 1
fi

filename=$(basename -- "$input_file")
extension="${filename##*.}"
filename="${filename%.*}"

output_file="${filename}_subtitled.${extension}"

ffmpeg -i "$input_file" -vf subtitles="$input_srt" -preset ultrafast -c:a copy "$output_file"

if [ $? -eq 0 ]; then
    echo "Subtitles added successfully. Output file: '$output_file'"
else
    echo "Failed to add timecode."
    exit 1
fi


