version: "3.8"
services:
  gpu-jupyter:
    container_name: gpu-jupyter
    image: cschranz/gpu-jupyter:v1.5_cuda-11.6_ubuntu-20.04
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/jovyan/work
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
    user:
      "root"
    restart: unless-stopped