version: "3"

services:
  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb:latest
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:password@host.docker.internal:5432/postgres?sslmode=disable
    ports:
      - 8081:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s
