services:
  mount-checker:
    build: mount-checker
    container_name: nextcloud-checker
    volumes:
      - /media/veracrypt1:/media/veracrypt1
    healthcheck:
      test: ["CMD-SHELL", "mountpoint -q /media/veracrypt1"]
      interval: 5s
      timeout: 5s
      start_period: 0s
      retries: 2147483647
    restart: unless-stopped

  mount-runner:
    build: mount-runner
    container_name: nextcloud-runner
    depends_on:
      mount-checker:
        condition: service_healthy
    volumes:
      - /media/veracrypt1:/media/veracrypt1
    restart: unless-stopped
  
  db:
    image: mariadb:10.6
    container_name: nextcloud-db
    depends_on:
      mount-checker:
        condition: service_healthy
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  app:
    build: .
    container_name: nextcloud-app
    depends_on:
      mount-checker:
        condition: service_healthy
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html
      - /media/veracrypt1:/opt/mount
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS="localhost 10.152.153.14 10.152.152.14"
    restart: unless-stopped
