version: '3'
services:
  kaggle:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./working:/opt/working:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
