worker_processes auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    # Prevent nginx HTTP Server Detection
    server_tokens   off;

    keepalive_timeout  65;

    # # Set the `immutable` cache control options only for assets with a cache busting `v` argument
    # map $arg_v $asset_immutable {
    #     "" "";
    # default "immutable";
    # }

    # #gzip  on;

    # upstream php-handler {
    #     server app:9000;
    # }

    server {
        client_max_body_size 16G;

        listen 80;

        location / {
            proxy_pass http://host.docker.internal:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto http;
            proxy_read_timeout 60;
            proxy_connect_timeout 60;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        client_max_body_size 16G;
        server_name nextcloud.local;
        listen 443 ssl;
        ssl_certificate /etc/ssl/certs/cert.crt;
        ssl_certificate_key /etc/ssl/private/cert.key;

        location / {
            proxy_pass http://host.docker.internal:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_read_timeout 60;
            proxy_connect_timeout 60;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
