worker_processes auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    # Prevent nginx HTTP Server Detection
    server_tokens   off;

    keepalive_timeout  65;

    # # Set the `immutable` cache control options only for assets with a cache busting `v` argument
    # map $arg_v $asset_immutable {
    #     "" "";
    # default "immutable";
    # }

    # #gzip  on;

    # upstream php-handler {
    #     server app:9000;
    # }

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name nextcloud.local;

        ssl_certificate /etc/ssl/certs/cert.crt;
        ssl_certificate_key /etc/ssl/private/cert.key;

        client_max_body_size 0;
        underscores_in_headers on;

        location ~ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header Front-End-Https on;

            proxy_headers_hash_max_size 512;
            proxy_headers_hash_bucket_size 64;

            proxy_buffering off;
            proxy_redirect off;
            proxy_max_temp_file_size 0;
            proxy_pass http://host.docker.internal:8080;
        }
    }
}
