#!/bin/bash

if ! [[ $EUID -ne 0 ]]; then
	echo "This script should not be run with root/sudo privileges."
	exit 1
fi

CUR_USER=$(whoami)

START=1
if [ $# -ge 2 ]; then
	echo "Usage: filebrowser <start|stop>"
	exit 1
fi
if [ $# -eq 0 ]; then
	START=1
fi
if [ "$1" == "stop" ]; then
    START=0
elif [ "$1" == "start" ]; then
    START=1
else
   	echo "Usage: filebrowser <start|stop>"
	exit 1
fi

DIRECTORY="/home/$CUR_USER/programs/filebrowser/"

if (( START )); then
    docker-compose --project-directory $DIRECTORY up -d --build
else
    docker-compose --project-directory $DIRECTORY stop
fi

echo "The default login credentials are admin:admin"