services:
  nginxwebdav:
    container_name: nginxwebdav
    build:
      context: .
    volumes:
      - /media:/data:ro
      - ./config:/config
    environment:
      - TZ=Americas/Toronto
      - WEBDAV_USERNAME=
      - WEBDAV_PASSWORD=
      - SERVER_NAMES=localhost,10.152.153.14,10.152.152.14
      - TIMEOUTS_S=1200 # these are seconds
    ports:
      - 80:80
    restart: unless-stopped
