client                                                                                                  
nobind                                                                                                    
dev tun                                                                                                     
remote-cert-tls server                                                                                       
                                                                                                               
remote 10.153.153.15 1194 udp                                                                                   
                                                                                                                   
<key>                                                                                                           
</key>
<cert>
</cert>
<ca>
</ca>
key-direction 1
<tls-auth>
</tls-auth>

redirect-gateway def1