#!/bin/bash

PROGRAM_NAME="openvpn"

if ! [[ $EUID -ne 0 ]]; then
	echo "This script should not be run with root/sudo privileges."
	exit 1
fi

CUR_USER=$(whoami)

START=1
if [ $# -ge 2 ]; then
	echo "Usage: $PROGRAM_NAME <start|stop>"
	exit 1
fi
if [ $# -eq 0 ]; then
	START=1
elif [ "$1" == "stop" ]; then
    START=0
elif [ "$1" == "start" ]; then
    START=1
else
   	echo "Usage: $PROGRAM_NAME <start|stop>"
	exit 1
fi

DIRECTORY="/home/$CUR_USER/programs/$PROGRAM_NAME/docker-compose.yaml"

if (( START )); then
    docker-compose --file $DIRECTORY up -d --build
else
    docker-compose --file $DIRECTORY stop
fi