version: "3"
services:
  zalenium:
    image: dosel/zalenium
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: zalenium
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./videos:/home/seluser/videos
    privileged: true
    command: start
